#%RAML 1.0 NamedExample

name: "Metallica - Master of puppets"
description: "Master of Puppets is the third studio album by the American heavy metal band Metallica, released on March 3, 1986, by Elektra Records."
unit_price: 19.99
image_url: "https://cdn-icons-png.flaticon.com/512/32/32328.png"
active: true
units_in_stock: 20
category:
  id: 1
  category_name: CD